FROM buildenv

# Install MoCOCrW dependencies (except OpenSSL)
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
        # for pkcs11-tool which we use to create keys in token
        opensc \
        # p11-kit-modules allows loading of libp11 engine without having to edit openssl.cnf
        p11-kit-modules \
        # softhsm2: includes both softhsm2-util and libsofthsm2
        softhsm2 \
        && rm -rf /var/lib/apt/lists/*

RUN cd /tmp && \
    wget https://github.com/OpenSC/libp11/releases/download/libp11-0.4.12/libp11-0.4.12.tar.gz && \
    tar xvf libp11-0.4.12.tar.gz && \
    cd libp11-0.4.12 && \
    ./configure && make -j$(nproc) && make install

